#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

cat > /etc/apt/sources.list.d/debian-sid-source.sources <<'SOURCES'
Types: deb-src
URIs: http://deb.debian.org/debian
Suites: sid
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp
SOURCES

apt-get update
