#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

self="$(realpath "$0")"
scripts="$(dirname "$self")"
sid_version="$("${scripts}/sid-version")"
rebuild_version="${sid_version}~trixie1"
rebuild_without_epoch="${rebuild_version#*:}"

printf 'sid-version=%s\n' "$sid_version"
printf 'rebuild-version=%s\n' "$rebuild_version"
printf 'tag=%s\n' "${rebuild_without_epoch//\~/-}"
